version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/tomato_disease_analyzer
    overwrite: yes

permission:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runs: ubuntu