server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    url: jdbc:mariadb://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DB_NAME}?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      format_sql: true
    properties:
      '[hibernate.default_batch_fetch_size]': 100
  sql:
    init:
      mode: always
logging:
  level:
    tomato.tomato.classifier: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
